'use client';

import { useEffect, useMemo, useState } from 'react';

const API = process.env.NEXT_PUBLIC_FINCLOSE_API_URL || 'https://phhpiqwvgwlgjmyiksqe.supabase.co/functions/v1/finclose-lab-api';

type Country = { code:string; name:string; currency:string };
type InitRecord = { initialization_id:string; filename:string; legal_name?:string; country?:string; country_code?:string; country_name?:string; service_scope?:string; status:string; ready:boolean; blockers?:{message:string}[]; warnings?:{message:string}[] };
type Company = { company_id:string; legal_name:string; country_code:string; country_name:string; service_scope:string; status:string };

async function api(path:string, init?:RequestInit) {
  const r = await fetch(API + path, init);
  const text = await r.text();
  let data:any;
  try { data = JSON.parse(text); } catch { data = { detail:text }; }
  if (!r.ok) throw new Error(data.detail || text || `HTTP ${r.status}`);
  return data;
}
function toBase64(file:File) { return new Promise<string>((resolve,reject)=>{ const reader=new FileReader(); reader.onload=()=>resolve(String(reader.result).split(',')[1]||''); reader.onerror=()=>reject(reader.error); reader.readAsDataURL(file); }); }

export default function Home() {
  const [countries,setCountries]=useState<Country[]>([]); const [country,setCountry]=useState('GE'); const [email,setEmail]=useState('');
  const [download,setDownload]=useState(''); const [reqNote,setReqNote]=useState('Ready.'); const [uploadNote,setUploadNote]=useState('No file uploaded.'); const [dataNote,setDataNote]=useState('Awaiting initialized company.');
  const [records,setRecords]=useState<InitRecord[]>([]); const [companies,setCompanies]=useState<Company[]>([]); const [companyId,setCompanyId]=useState(''); const [stage,setStage]=useState('bookkeeping');
  const [initFile,setInitFile]=useState<File|null>(null); const [dataFile,setDataFile]=useState<File|null>(null); const [health,setHealth]=useState('Checking persistence…');
  const ready=useMemo(()=>records.filter(r=>r.ready).length,[records]); const blocked=records.length-ready;

  async function refreshCompanies(){ const list:Company[]=await api('/companies'); setCompanies(list); setCompanyId(v=>v&&list.some(c=>c.company_id===v)?v:(list[0]?.company_id||'')); }
  useEffect(()=>{(async()=>{try{const [cs,h]=await Promise.all([api('/initialization/countries'),api('/health')]);setCountries(cs);setHealth(`Supabase persistence active · ${h.version}`);await refreshCompanies();}catch(e:any){setHealth('Backend error: '+e.message)}})()},[]);
  async function requestTemplate(){setReqNote('Requesting…');try{const d=await api('/initialization/template/request',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({country,email})});setDownload(d.download_url||'');setReqNote(d.note||'Template ready.')}catch(e:any){setReqNote('Error: '+e.message)}}
  async function uploadInitialization(){if(!initFile)return setUploadNote('Choose an XLSX or ZIP first.');setUploadNote('Validating and saving…');try{const d=await api('/initialization/upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({filename:initFile.name,content_base64:await toBase64(initFile)})});setRecords(r=>[...r,...d.records]);setUploadNote(`Validated ${d.records.length} template(s) and persisted the result.`)}catch(e:any){setUploadNote('Error: '+e.message)}}
  async function initializeOne(id:string){try{const d=await api(`/initialization/${id}/initialize`,{method:'POST'});setRecords(r=>r.map(x=>x.initialization_id===id?d:x));await refreshCompanies();setUploadNote(`${d.legal_name||'Company'} initialized and stored in Supabase.`)}catch(e:any){setUploadNote('Error: '+e.message)}}
  async function initializeAll(){const ids=records.filter(r=>r.ready&&r.status!=='INITIALIZED').map(r=>r.initialization_id);if(!ids.length)return setUploadNote('No uninitialized READY companies.');try{const d=await api('/initialization/initialize-ready',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initialization_ids:ids})});const map=new Map<string,InitRecord>(d.initialized.map((x:InitRecord)=>[x.initialization_id,x]));setRecords(r=>r.map(x=>map.get(x.initialization_id)||x));await refreshCompanies();setUploadNote(`Initialized ${d.initialized.length}; blocked ${d.blocked.length}.`)}catch(e:any){setUploadNote('Error: '+e.message)}}
  async function uploadChunk(){if(!companyId)return setDataNote('Initialize a company first.');if(!dataFile)return setDataNote('Choose a data file.');setDataNote('Uploading to persistent storage…');try{const d=await api(`/companies/${companyId}/data-chunks`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stage,filename:dataFile.name,content_base64:await toBase64(dataFile)})});const rows=d.metadata?.sheet_rows?Object.values(d.metadata.sheet_rows).reduce((a:any,b:any)=>Number(a)+Number(b),0):null;setDataNote(`${d.status}: ${d.filename} · ${d.bytes} bytes · ${d.country_name} context${rows?` · ${rows} non-empty spreadsheet rows`:''} · SHA ${String(d.sha256).slice(0,12)}…`)}catch(e:any){setDataNote('Error: '+e.message)}}

  return <><header className="top"><div className="topin"><div className="brand"><div className="logo">F</div><div><b>FinClose Lab</b><small>Firebase deployment candidate</small></div></div><div className="pills"><span className="pill">Firebase Hosting</span><span className="pill">v0.22</span><span className="pill">Supabase data</span></div></div></header><main className="shell">
    <section className="hero"><div><span className="eyebrow">COMPANY INITIALIZATION + DATA TAKEOVER</span><h1>Test FinClose on Firebase.</h1><p>The web client is isolated for Firebase deployment while the already-tested company state, audit trail and uploaded files remain in Supabase.</p></div><aside className="safe"><b>Backend check</b><p className={health.startsWith('Supabase')?'good':''}>{health}</p><p>Synthetic/test data only until authentication is added.</p></aside></section>
    <section className="grid">
      <div className="card"><div className="head"><h2>1 · Request initialization template</h2><p>Choose a jurisdiction and download the Lab workbook.</p></div><div className="body"><div className="row"><label className="label"><span>Country</span><select className="select" value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="label"><span>Email (optional)</span><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="finance@example.com"/></label></div><div className="actions"><button className="button primary" onClick={requestTemplate}>Request template</button>{download&&<a href={download}><button className="button secondary">Download directly</button></a>}</div><div className="note" style={{marginTop:12}}>{reqNote}</div></div></div>
      <div className="card"><div className="head"><h2>2 · Validate and initialize company</h2><p>Upload XLSX/ZIP; READY records can be initialized.</p></div><div className="body"><label className="label"><span>Initialization file</span><input className="input file" type="file" accept=".xlsx,.zip" onChange={e=>setInitFile(e.target.files?.[0]||null)}/></label><div className="actions"><button className="button primary" onClick={uploadInitialization}>Validate upload</button><button className="button secondary" onClick={initializeAll}>Initialize all ready</button></div><div className="note" style={{marginTop:12}}>{uploadNote}</div></div></div>
      <div className="card full"><div className="head"><h2>Initialization review</h2><p>Validation results are persisted before company creation.</p></div><div className="body"><div className="stats"><span className="stat">{records.length} uploaded</span><span className="stat">{ready} ready</span><span className="stat">{blocked} blocked</span></div><div className="tablewrap"><table><thead><tr><th>Status</th><th>Company</th><th>Country</th><th>Scope</th><th>Validation</th><th>Action</th></tr></thead><tbody>{records.length?records.map(r=><tr key={r.initialization_id}><td><span className={`badge ${r.ready?'ok':'bad'}`}>{r.status}</span></td><td><b>{r.legal_name||r.filename}</b><br/><span className="muted">{r.filename}</span></td><td>{r.country_name||r.country_code||r.country}</td><td>{r.service_scope||'—'}</td><td>{r.ready?(r.warnings?.length?<span className="badge warn">{r.warnings.length} warning</span>:'No blockers'):(r.blockers||[]).slice(0,3).map((b,i)=><div key={i}>{b.message}</div>)}</td><td>{r.ready&&r.status!=='INITIALIZED'?<button className="button secondary" onClick={()=>initializeOne(r.initialization_id)}>Initialize</button>:'—'}</td></tr>):<tr><td colSpan={6} className="muted">Upload a template to begin.</td></tr>}</tbody></table></div></div></div>
      <div className="card"><div className="head"><h2>3 · Persistent companies</h2><p>Reload after deployment: initialized companies must remain.</p></div><div className="body"><div className="tablewrap"><table><thead><tr><th>Company</th><th>Country</th><th>Scope</th><th>Status</th></tr></thead><tbody>{companies.length?companies.map(c=><tr key={c.company_id}><td><b>{c.legal_name}</b></td><td>{c.country_name}</td><td>{c.service_scope}</td><td><span className="badge ok">{c.status}</span></td></tr>):<tr><td colSpan={4} className="muted">No initialized companies.</td></tr>}</tbody></table></div><div className="actions"><button className="button secondary" onClick={refreshCompanies}>Refresh backend</button></div></div></div>
      <div className="card"><div className="head"><h2>4 · Upload company data</h2><p>The company provides jurisdiction context; files stay in private Supabase Storage.</p></div><div className="body"><div className="row"><label className="label"><span>Company</span><select className="select" value={companyId} onChange={e=>setCompanyId(e.target.value)}>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.legal_name} · {c.country_name}</option>)}</select></label><label className="label"><span>Stage</span><select className="select" value={stage} onChange={e=>setStage(e.target.value)}><option value="bookkeeping">Bookkeeping</option><option value="opening_state">Opening state</option><option value="master_data">Master data</option><option value="payroll">Payroll</option></select></label></div><label className="label"><span>Data file</span><input className="input file" type="file" onChange={e=>setDataFile(e.target.files?.[0]||null)}/></label><div className="actions"><button className="button primary" onClick={uploadChunk}>Upload chunk</button></div><div className="note" style={{marginTop:12}}>{dataNote}</div></div></div>
    </section><div className="footer">FinClose Lab v0.22 · Firebase deployment candidate · Supabase persistence · synthetic-data test environment</div>
  </main></>;
}
