from pathlib import Path
p=Path('lib/close-governance-engine.ts')
s=p.read_text()

def rep(old,new,label):
    global s
    if old not in s: raise SystemExit(f'missing {label}')
    s=s.replace(old,new,1)

rep("function accountKey(accountCode: string) {\n  return crypto.createHash('sha256').update(accountCode).digest('hex').slice(0, 24);\n}\n", "function accountKey(accountCode: string) {\n  return crypto.createHash('sha256').update(accountCode).digest('hex').slice(0, 24);\n}\n\nfunction balanceScopeFingerprint(scope: Record<string, any>[]) {\n  return fingerprint(scope.map(item => ({\n    account_code: String(item.account_code || ''),\n    account_name: item.account_name || null,\n    category: String(item.category || ''),\n    material: item.material !== false,\n    tolerance: Number(item.tolerance || 0)\n  })));\n}\n", 'scope fingerprint helper')

rep("export async function recordPeriodSourceEvidence(deploymentId: string, input: PeriodSourceEvidenceInput) {\n  await getServiceDeployment(deploymentId);\n  const evidenceId", "export async function recordPeriodSourceEvidence(deploymentId: string, input: PeriodSourceEvidenceInput) {\n  const deployment = await getServiceDeployment(deploymentId) as Record<string, any>;\n  const evidenceId", 'source evidence deployment')
rep("  if (periodStart > periodEnd) throw httpError('period_start must not be after period_end', 400);\n  if (coverageStart > coverageEnd)", "  if (periodStart > periodEnd) throw httpError('period_start must not be after period_end', 400);\n  if (deployment.company_id) await assertDateRangeOpenForCompany(String(deployment.company_id), periodStart, periodEnd, 'source evidence');\n  if (coverageStart > coverageEnd)", 'source evidence period lock')

rep("  const now = Date.now();\n  const records = Object.fromEntries(normalized.map(item => [accountKey(item.account_code), { ...item, deployment_id: deploymentId, updated_at: now }]));\n  const db = realtimeDatabase();\n  await db.ref(`finclose_balance_sheet_scope/${deploymentId}`).set(records);", "  const now = Date.now();\n  const scopeFingerprint = balanceScopeFingerprint(normalized);\n  const records = Object.fromEntries(normalized.map(item => [accountKey(item.account_code), { ...item, deployment_id: deploymentId, updated_at: now }]));\n  const db = realtimeDatabase();\n  await db.ref().update({\n    [`finclose_balance_sheet_scope/${deploymentId}`]: records,\n    [`finclose_balance_sheet_scope_meta/${deploymentId}`]: { deployment_id: deploymentId, scope_fingerprint: scopeFingerprint, account_count: normalized.length, material_account_count: normalized.filter(item => item.material).length, updated_at: now }\n  });", 'scope meta write')
rep("  return { deployment_id: deploymentId, accounts: normalized, updated_at: now };", "  return { deployment_id: deploymentId, scope_fingerprint: scopeFingerprint, accounts: normalized, updated_at: now };", 'scope return')

rep("  const { close } = await requireClose(deploymentId, closeId);\n  const scopeSnap", "  const { close } = await requireClose(deploymentId, closeId);\n  if (String(close.close_status || '') === 'LOCKED') throw httpError('locked close reconciliation is immutable; reopen the period first', 409);\n  if (String(close.close_status || '') === 'REOPENED') throw httpError('reopened close requires a new close version before reconciliation', 409);\n  const scopeSnap", 'recon immutable guard')
rep("  const result = calculateBalanceSheetReconciliation(scope, entries);\n  const now", "  const scopeFingerprint = balanceScopeFingerprint(scope);\n  const result = calculateBalanceSheetReconciliation(scope, entries);\n  const now", 'recon scope fingerprint')
rep("    balance_sheet_reconciliation_id: `${closeId}__balance-sheet`,\n    deployment_id", "    balance_sheet_reconciliation_id: `${closeId}__balance-sheet`,\n    scope_fingerprint: scopeFingerprint,\n    deployment_id", 'recon record scope fingerprint')

rep("export async function evaluateSourceCompleteness(deploymentId: string, closeId: string) {\n  const { close } = await requireClose(deploymentId, closeId);\n  const result", "export async function evaluateSourceCompleteness(deploymentId: string, closeId: string) {\n  const { close } = await requireClose(deploymentId, closeId);\n  if (String(close.close_status || '') === 'LOCKED') throw httpError('locked close source evidence is immutable; reopen the period first', 409);\n  if (String(close.close_status || '') === 'REOPENED') throw httpError('reopened close requires a new close version before source evaluation', 409);\n  const result", 'source eval immutable guard')

rep("export async function refreshCloseGovernance(deploymentId: string, closeId: string) {\n  const { close } = await requireClose(deploymentId, closeId);\n  const source = await evaluateSourceCompleteness", "export async function refreshCloseGovernance(deploymentId: string, closeId: string) {\n  const { close } = await requireClose(deploymentId, closeId);\n  if (String(close.close_status || '') === 'LOCKED') {\n    return { monthly_close_id: closeId, status: close.status, approval_status: close.approval_status, layer_a: close.layer_a || null };\n  }\n  const source = await evaluateSourceCompleteness", 'locked governance immutability')
rep("  const balanceSheet = await loadBalanceSheetReconciliation(closeId);\n  const corePass", "  const balanceSheet = await loadBalanceSheetReconciliation(closeId);\n  const scopeSnap = await realtimeDatabase().ref(`finclose_balance_sheet_scope/${deploymentId}`).once('value');\n  const currentScope = scopeSnap.exists() ? Object.values(scopeSnap.val() as Record<string, any>) as Record<string, any>[] : [];\n  const currentScopeFingerprint = currentScope.length ? balanceScopeFingerprint(currentScope) : null;\n  const scopeMatches = Boolean(balanceSheet && currentScopeFingerprint && String(balanceSheet.scope_fingerprint || '') === currentScopeFingerprint);\n  const corePass", 'scope current load')
rep("  const balanceSheetPass = String(balanceSheet?.status || '') === 'PASS';\n  const blockers = [", "  const balanceSheetPass = String(balanceSheet?.status || '') === 'PASS' && scopeMatches;\n  const blockers = [", 'scope pass')
rep("    ...(balanceSheet ? (balanceSheet.exceptions || []).map((item: string) => `BALANCE_SHEET:${item}`) : ['BALANCE_SHEET:NOT_PREPARED'])\n  ];", "    ...(balanceSheet ? (balanceSheet.exceptions || []).map((item: string) => `BALANCE_SHEET:${item}`) : ['BALANCE_SHEET:NOT_PREPARED']),\n    ...(balanceSheet && !scopeMatches ? ['BALANCE_SHEET:SCOPE_CHANGED_RECONCILIATION_REQUIRED'] : [])\n  ];", 'scope blocker')
rep("    balance_sheet_reconciliation_status: balanceSheet?.status || 'NOT_PREPARED',", "    balance_sheet_reconciliation_status: balanceSheet?.status || 'NOT_PREPARED',\n    balance_sheet_scope_fingerprint: currentScopeFingerprint,\n    balance_sheet_scope_matches_reconciliation: scopeMatches,", 'layer a scope metadata')

rep("    evidence_hash: evidenceHash,\n    status: 'APPROVED',", "    evidence_hash: evidenceHash,\n    evidence_snapshot: snapshot,\n    status: 'APPROVED',", 'approval snapshot')
rep("    approval_evidence_hash: currentHash,\n    status: 'LOCKED',", "    approval_evidence_hash: currentHash,\n    evidence_snapshot: snapshot,\n    status: 'LOCKED',", 'lock snapshot')

p.write_text(s)
